import Head from "next/Head";

export default function Home() {
  return (
    <>
      <Head>
        <title>SpaceLab | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Welcome to the home page!</main>
    </>
  );
}
